[functions.cmc-prices]
enabled = true
verify_jwt = false
import_map = "./functions/cmc-prices/deno.json"
entrypoint = "./functions/cmc-prices/index.ts"

[functions.check-entry-alerts]
enabled = true
verify_jwt = false
import_map = "./functions/check-entry-alerts/deno.json"
entrypoint = "./functions/check-entry-alerts/index.ts"

[functions.cmc-entry]
enabled = true
verify_jwt = true
import_map = "./functions/cmc-entry/deno.json"
entrypoint = "./functions/cmc-entry/index.ts"

[functions.save-cmc-key]
enabled = true
verify_jwt = true
import_map = "./functions/save-cmc-key/deno.json"
entrypoint = "./functions/save-cmc-key/index.ts"

[functions.test-push]
enabled = true
verify_jwt = true
import_map = "./functions/test-push/deno.json"
entrypoint = "./functions/test-push/index.ts"

[functions.send-entry-push]
verify_jwt = false



[functions.update-token-prices]
enabled = true
verify_jwt = true
import_map = "./functions/update-token-prices/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-token-prices/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-token-prices/*.html" ]
